# Generated by Django 4.1 on 2022-08-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개여부'),
        ),
    ]
