# Generated by Django 4.1 on 2022-09-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram1', '0002_post_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
